config/routes.rb
Rails.application.routes.draw do
  
  root 'home#top'
  get 'home/about' => 'home#about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	 resource :favorites, only: [:create, :destroy]
  	resources :post_comments, only: [:create, :destroy]
  end

  get "following_posts" => "posts#following_posts"

  resources :users, only: [:show, :index, :edit, :update] do
  	resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
end

  resources :notifications, only: :index

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  #　フォロー機能
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  # foreign_keyは入口で、sourceが出口
  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end


   def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  attachment :profile_image
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
    @posts = @user.posts.where(status: 0)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
  else
    render action: :edit
  end
  end

  private

 def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

   def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless @user == current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<div class="col-xs-9">
	<h2>やらない人々</h2>

<table class='table'>
  <thead>
    <tr>
      <th>ポートフォリオ対策のアイコン機能</th>
      <th>ニックネーム</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
         <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
								
        <td><%= user.name %></td>

        <td>フォロー数：<%= user.follower.count %></td>
        <td>フォロワー数：<%= user.followed.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
            <% end %>
          <% end %>
        </td>
       
        
        <% if user != current_user %>
          <td><%= link_to 'この人のBekaras', user, class: "user_#{user.id}" %></td>
        <% else %>
          <td><%= link_to 'マイページへ', user, class: "user_#{user.id}" %></td>
        <% end %>
      

      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/users/_info.html.erb
<h2>やらない人</h2>
				<!-- ここにプロフィール画像 -->
				<div class="profile-container">
    					<%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>  
						
				</div>
				
				<table class="table">
					<tbody>
						<tr>
							<th>Nickname</th>
							<th><%= user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= user.introduction %></th>
						</tr>

						<tr>
							<th>follows</th>
							<th><%= link_to user.follower.count, user_follows_path(user) %></th>
						</tr>

						<tr>
							<th>followers</th>
							<th><%= link_to user.followed.count, user_followers_path(user) %></th>
						</tr>

						
					</tbody>
					
				</table>
				<!-- follow button -->
				<% if current_user != user %> 
  					<% if current_user.following?(user) %> 
    					<%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
  					<% else %>
    					<%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class: "btn btn-success" %>
  					<% end %>
  				<% end %>
				
				<!-- プロフィール編集ページへのリンク -->
				<div class="row">
					<% if user == current_user %>
  						<div class='row'>
    						<%= link_to '',edit_user_path(user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
  						</div>
					<% end %>
					

				</div>

app/views/users/edit.html.erb
<div class="body">
	<div class="container">
		<p id="notice"></p>
		<h2>User info</h2>

		<%= form_for(@user) do |f| %>
			<!-- エラーメッセ -->
			<% if @user.errors.any? %>
				<h3><%= @user.errors.count %>1 error prohibited this obj from being saved:</h3>
    				<ul>
      					<% @user.errors.full_messages.each do |message| %>
        				<li><%= message %></li>
     					<% end %>
    				</ul>
			<% end %>
		
			<h4>Name</h4>
				<%= f.text_field :name %>

			<div class="form-group has-icon">
    			<div class="user-edit-image">
        			<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
    			</div>
    			<label class="control-label sr-only" for="inputEmail">ProfileImage</label>
    				<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
			</div>                                                   

			<h4>Opinion</h4>
				<%= f.text_area :introduction %>
	
			<%= f.submit 'Update User' %>
		
		<% end %>
		
	</div>
	
</div>

app/views/users/index.html.erb
<div class="body">
	<div class="container">
		<p id="notice"></p>

		<div class="row">
			<div class="col-xs-3">
				<%= render 'users/info', user: current_user %>
				<!-- 新規投稿部分（共通テンプレ） -->
				
			</div>

			<!-- ログインユーザーの投稿一覧 -->

			<%= render 'index',users: @users %>
			
		</div>
		
	</div>
	
</div>

app/views/users/show.html.erb
<div class="body">
	<div class="container">
		<p id="notice"></p>
		
		<div class="row">
		<%= flash[:notice] %>
			<div class="col-xs-3">
				<%= render 'users/info', user: @user %>
				<!-- user information -->
				
			</div>

			<!-- ログインユーザーの投稿一覧 -->
			<div class="col-xs-7">

				<% if current_user != @user %>
					<%= @user.name + "さんの挑むBekaras" %>
				<% else %>
						<p>あなたが今、挑戦しているBekarasです</p>
				<% end %>
				
			
			 <%= render 'posts/index',posts: @posts %>
			 
			</div>
			
		</div>
		
	</div>
	
</div>