config/routes.rb
Rails.application.routes.draw do
  
  root 'home#top'
  get 'home/about' => 'home#about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	 resource :favorites, only: [:create, :destroy]
  	resources :post_comments, only: [:create, :destroy]
  end

  get "following_posts" => "posts#following_posts"

  resources :users, only: [:show, :index, :edit, :update] do
  	resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
end

  resources :notifications, only: :index

end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :post_comments, dependent: :destroy

	has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def create_notification_favorite!(current_user)
    # whereでいいねされているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
      #valid?はエラーなしでtrue、エラーありでfalseになるメソッド
    end
  end

  def create_notification_post_comment!(current_user, post_comment_id)
    # コメントしている人をすべて取得、where.not(user_id: current_user.id)で自分を除外。全員に通知を送る
    #selectしてdistinctで重複を解消
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_post_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # 誰もコメントしていない時、投稿者に通知
    #後置ifでも可能
    save_notification_post_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_post_comment!(current_user, post_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!
	before_action :correct_user, only: [:edit, :update, :destroy]
	
	def new
		@post = Post.new
	end

	def index
		@posts = Post.page(params[:page])
  		@search = Post.ransack(params[:q])
  		@q_posts = @search.result.page(params[:page])
	end

	def show
		@post = Post.find(params[:id])
		@post_comment = PostComment.new
    	@post_comments = @post.post_comments
	end

	# フォローユーザーのみの投稿一覧（タイムライン）（この書き方でフォローしているユーザーは持ってこれたっぽい）

	def following_posts
		@user = current_user
		@users = @user.following_user
	end

	def create
		 @post = Post.new(post_params)
    	@post.user_id = current_user.id
  	if @post.save
    	flash[:notice] = "Bekarasを作成しました"
    	redirect_to post_path(@post.id)
  	else
    	@posts = Post.all
    
    	render action: :index 
  	end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
    if @post.update(post_params)
        flash[:notice] = "更新しました"
       redirect_to post_path(@post.id)
  	else
      
      render action: :edit
  	end
	end

	def destroy
		 @post = Post.find(params[:id])
    	@post.destroy
    	redirect_to posts_url
	end

	def correct_user
  		@post = current_user.posts.find_by(id: params[:id])
    	unless @post
      		redirect_to posts_path
    	end
	end

	private
	def post_params
		params.require(:post).permit(:body, :event, :category, :status, :start_time)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<% post_comments.each do |post_comment| %> <!-- コメント一覧 -->
  <tr>
    <td>
      <%= link_to user_path(post_comment.user), class: "user_#{post_comment.user.id}" do %>
        <%= attachment_image_tag post_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
        <%= post_comment.user.name %>
      <% end %>
    </td>
    <td><%= post_comment.comment %></td>
    <% if post_comment.user == current_user %>
      <td><%= link_to 'Destroy', post_post_comment_path(post_comment.post, post_comment), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
    <% end %>
  </tr>
<% end %>

app/views/posts/_detail.html.erb
						


						<td>
							<%= link_to user_path(post.user_id) do %>
							<%= attachment_image_tag post.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>  
							<p><%= post.user.name + "さん"%></p>
							<% end %>
								
						</td>
								
						
						
							<td><%= post.body %></td> 
								
							

							
								
							<td><%= post.category == 0 ? "なんてしない" : "とか言わない" %></td>
							<td><%= post.event %></td>

							<td><%= post.status == 0 ? "未達成" : "達成" %></td>

							<td>
          
          						<% if post.favorited_by?(current_user) %>
            						<%= link_to post_favorites_path(post, redirect_id: 0), method: :delete, remote: true do %>
              						<span class="glyphicon glyphicon-heart"><%= post.favorites.count%></span>
            						<% end %>
          								
          							<% else %>
            							
            						<%= link_to post_favorites_path(post, redirect_id: 0), method: :post, remote: true do %>
              						<span class="glyphicon glyphicon-heart-empty"><%= post.favorites.count %></span>
            						<% end %>
          						<% end %>
        					</td>

							<% if post.user == current_user %>
							<td><%= link_to '達成確認', edit_post_path(post), class: "btn btn-primary" %></td>
							<td><%= link_to '削除', post, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn-sm btn-danger destroy_book_#{post.id}"%></td>
							<% end %>
						
								
						
								
							

app/views/posts/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% posts.each do |post| %>
      <tr class="post_<%= post.id %>">
        
        <%= render '/posts/post', post: post %>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/_post.html.erb
        
        
          
          <td><%= link_to post.body, post_path(post.id) %></td>
          
          <% if post.category == 0 %>
          <td>なんてしない</td>
          <% else %>
          <td>とか言わない</td>
          <% end %>
          <td><%= post.start_time %></td>
        <td>
          
                <% if post.favorited_by?(current_user) %>
                  <%= link_to post_favorites_path(post, redirect_id: 0), method: :delete, remote: true do %>
                    <span class="glyphicon glyphicon-heart"><%= post.favorites.count%></span>
                  <% end %>
                          
                  <% else %>
                          
                  <%= link_to post_favorites_path(post, redirect_id: 0), method: :post, remote: true do %>
                    <span class="glyphicon glyphicon-heart-empty"><%= post.favorites.count %></span>
                  <% end %>
                <% end %>
          </td>

          

app/views/posts/_search.html.erb
<%= search_form_for search do |f| %>
  <%= f.label :body, "Keyword" %>
  <%= f.search_field :body_cont %>

   <%= f.label :category %>
　
  <%= f.radio_button :category_eq, 0 %>行動
  <%= f.radio_button :category_eq, 1 %>言葉


  <%= f.submit "検索" %>
<% end %>

app/views/posts/edit.html.erb
<div class="body">
	<div class="container">
		<p id="notice"></p>

		<div class="row">
			
			<div class="col-md-6 col-md-offset-3">
				<h1>Bekaras達成確認</h1>

				<p>選択したBekaras</p>
				<h2><%= @post.body %></h2>
				<p>習慣化されたBekarasのステータスを「達成」に変更しましょう！</p>

				<%= form_for(@post) do |f| %>

					<% if @post.errors.any? %>
						<h3><%= @post.errors.count %>errors prohibited this book from being saved:</h3>
					<ul>
						<% @post.errors.full_messages.each do |message| %>
							<li><%= message %></li>
						<% end %>
					</ul>

					<% end %>

					
					
					<h4></h4>
					<%= f.label :status, "未達成" %>
					<%= f.radio_button :status, 0, checked: true %>
					<%= f.label :status, "達成" %>
					<%= f.radio_button :status, 1 %>

					<%= f.label :start_time %>
    				<%= f.datetime_select :start_time %>

					<%= f.submit 'Update Book' %>

				<% end %>

				<%= link_to "Show", post_path(@post) %>

							|

				<%= link_to "Back", posts_path %>
			
			</div>
		
		</div>

	</div>
	
</div>

app/views/posts/following_posts.html.erb
<div class="body">
<div class="container">
  <div class="row">
    <div class="col-xs-8">
      
          <caption>あなたがフォローしている人の投稿</caption>
          <% @users.each do |user| %>

            <% @posts = Post.where(user_id: user.id).order("created_at DESC").page(params[:page]).per(10) %>
          <table class="table">
            
            <thead>
              <tr>
                <th>投稿者</th>
                <th>タイトル</th>
                
              </tr>
            </thead>
            <tbody>
              <% @posts.each do |post| %>
                <tr>

              

                <td><%= link_to post.user.name + "さん", user_path(user.id) %></td>
            
                <td><%= link_to post.body,post, class: "post_#{post.id}" %></td>

                  <% if post.category == 0 %>
                    <td>なんてしない</td>
                  <% else %>
                    <td>とか言わない</td>
                  <% end %>
            
                  <%= paginate @posts, class: "paginate" %>

                </tr>
              <% end %>
            </tbody>
          </table>


          <% end %>
        </tr>

      
    </div>
  </div>

</div>
</div>

app/views/posts/index.html.erb
<div class="body">

  <div class="container">

<h2>投稿を検索する</h2>
<%= render 'search', search: @search %>

<%= month_calendar events: @posts do |date, posts| %>
  <%= date.day %>

  <% posts.each do |post| %>
    <div>
      <%= link_to post.body, post %>
    </div>
  <% end %>
  <%= paginate @posts, class: "paginate" %>
<% end %>

<% if @q_posts %>
  <%# 検索該当なしの場合 %>
  <div class="item-content">
    <% if @q_posts.empty? %>
      <div class="col-sm-9">
        <h3>投稿一覧</h3>
        <p class="top-empty-message">該当なし</p>
      </div>
    <% else %>
    <%# 検索該当ありの場合 %>
      <div class="col-sm-9">
        <h3>検索結果</h3>
        
        <%= render 'index', posts: @q_posts %>
        <div class="row text-center">
          <%= paginate @q_posts, class: "paginate" %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <%# 一覧表示の場合 %>
  <div class="col-sm-9">
    <h3>投稿一覧</h3>
    
    <%= render 'index', posts: @posts %>
    <div class="row text-center">
      <%= paginate @posts, class: "paginate" %>
    </div>
  </div>
  
<% end %>

  </div>

</div>

app/views/posts/new.html.erb
<div class="body">

	<div class="container">

	<div class="col-xs-10 col-xs-offset-1">

		<h1>Bekaras登録フォーム</h1>
		


		<%= form_for(@post, url: posts_path) do |f| %>

			

			<div class="form-group row">

				<%= f.label :body, "明日のBekaras" %>
				<%= f.text_field :body %>
			</div>

			<div class="form-group row">

				<h4>後に続く言葉を選択</h4>
				<%= f.label :category, "なんてしない" %>
				<%= f.radio_button :category, 0, checked: true %>
				<%= f.label :category, "とか言わない" %>
				<%= f.radio_button :category, 1 %>
			</div>
			
			<div class="form-group row">
				<%= f.label :event, "Bekarasにまつわるエピソード" %>
				<%= f.text_area :event,  rows:'5', class: "form-control",placeholder: "エピソードを入力してください" %>
			</div>
				
			<div class="form-group row">
				<h4>達成ステータス（新規登録時は未達成として登録されます）</h4>
				<%= f.label :status, "未達成" %>
				<%= f.radio_button :status, 0, checked: true %>
			</div>
			
			<div class="time">
				<span>作成時刻</span>
    			<%= f.datetime_select :start_time %>
    		</div>
		
				<%= f.submit '登録', class:"btn btn-primary" %>
		
			</div>

		<% end %>

	</div>

</div>

app/views/posts/show.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <p class="text"><%= flash[:notice] %></p>
      </div>
 <% end %>

<div class="body">
	<div class="container">
		<p id="notice"></p>

		<div class="row">

		
			

			<!-- ログインユーザーの投稿一覧 -->

			<div class="col-md-12">
				<h2>このBekarasについて</h2>

				<table class="table table-hover table-inverse">
					
					<thead>
						<tr>
							<th></th>
							<th>内容</th>
							<th></th>
							<th>エピソード</th>
							<th>達成状況</th>
							
							<th colspan="3"></th>
						</tr>
					</thead>
					<!-- 繰り返さない -->
					
						<tbody>
							<tr class="post_<%= @post.id %>">
								
								
								<%= render 'detail', post: @post %>
							

							</tr>
						</tbody>
					
				</table>
				
				<table class="show-tb comment_<%= @post.id %>">
					<%= render 'comment', post_comments: @post.post_comments %>
				</table>

				<%= form_with model:[@post, @post_comment], data: {remote: true} do |f| %>
					<%= f.text_area :comment,  rows:'5', class: "form-control",placeholder: "コメントをここに" %>
  					<%= f.submit 'コメントする' %>
				<% end %>
				
			</div>
		
			
		</div>
		
	</div>
	
</div>