config/routes.rb
Rails.application.routes.draw do
  
  root 'home#top'
  get 'home/about' => 'home#about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	 resource :favorites, only: [:create, :destroy]
  	resources :post_comments, only: [:create, :destroy]
  end

  get "following_posts" => "posts#following_posts"

  resources :users, only: [:show, :index, :edit, :update] do
  	resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
end

  resources :notifications, only: :index

end

app/views/layouts/_header.html.erb
<header class="py-4">
	
	<div class="container">

			<%= link_to(root_path, class:"header-logo") do %>

            	<nav class="nav navbar-nav navbar-left">
            		<!-- ここにイメージタグ -->
                	<h1>Bekaras</h1> 
            	</nav>
            <% end %>
		<!-- nav -->
		<ul class="nav nav-pills nav-fill navbar-right">

			<% if user_signed_in? %>

				<li><%= link_to "マイページ", user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>

				<li><%= link_to "新規投稿", new_post_path, class: "glyphicon glyphicon-book book" %></li>

				<li><%= link_to "投稿検索", posts_path, class: "glyphicon-book book" %></li>

				<li><%= link_to "タイムライン", following_posts_path %></li>


				<li><%= link_to "ユーザー一覧", users_path, class: "glyphicon glyphicon-user users" %></li>

				<li><%= link_to "お知らせ", notifications_path %></li>


				<li><%= link_to "logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>

			<% else %>

				<li><%= link_to "Home", root_path %></li>

				<li><%= link_to "About", home_about_path %></li>

				<li><%= link_to "会員登録", new_user_registration_path %></li>

				<li><%= link_to "ログインする", new_user_session_path %></li>


			<% end %>
			
		</ul>
		
	</div>
	
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bekaras</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

     
          
          <%= yield %>

        

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
              <p>CopyRight .inc</p>
          </div>
        </div>
      </div>
    </footer>
  
  </body>
</html>